service: backend-peranto
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-west-2:861318639742:table/Users

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  addUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get
  validateUser:
    handler: src/validateUser.validateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
